### ISSUE TITLE
Play or queue song

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#10]
It would be great if we could play instantly or "add to queue" a song directly from SpotifyFinder in the Windows client or web client.

**Comment by lfg6000** [comment]
definitely can see how this would be useful.  good suggestion.

technical notes:
- would have to start asking for 'user-modify-playback-state' permission 
  (this new permission would be listed in the Spotify login dialog, when the user presses 'login with spotify' )
- note from the spotify web 'play' and 'add_to_queue' api docs: 
   These API's only works for users who have Spotify Premium. 

plans:
- going to experiment with adding a 'play track' and 'add track to queue' buttons
- it may be a while before i can get to this experiment

**Comment by lfg6000** [comment]
added a Add to Queue, Play, Pause, Next buttons to the search, tracks, artists tabs.
Thanks for the suggestion.   Let me know if you find any issues.

**Comment by obetz** [comment]
It's really useful, thanks! Use case: I listen to a track in "discover weekly" and think "I already should have this somewhere" Fire up SpotifyFinder, find it in my playlists, add to queue, so can compare immediately.

**Comment by lfg6000** [comment]
excellent i was hoping that the add to queue might be useful.

here is my current understanding on how the spotify queue works:

on the first add to queue event (assuming the queue is empty)
- the track(s) you added will be at the top of the queue
- the track that is playing will continue. 
- the track(s) you added will start once the current track is finished
- to immediately hear the first track you added to the queue you can press next.

on subsequent add to queue events (assuming the queue is not empty...not all the previously added tracks have played)
- the track(s) are added to the bottom of the existing queue
- so pressing next will play a track that was previously added

on subsequent add to queue events (assuming the queue is empty...all the previously added tracks have been played)
- the track(s) you added will be at the top of the queue
- the track that is playing will continue. 
- the track(s) you added will start once the current track is finished
- to immediately hear the first track you added to the queue you can press next.
