### ISSUE TITLE
Making it load playlist tracks faster

### ISSUE THREAD

**Issue by haykkh** [lfg6000/SpotifyFinder#2]
Hi there! I made a similar project (https://github.com/haykkh/what-the-playlist). Well done with SpotifyFinder :) 

I wanted to note, regarding the slow loading time for a large volume of playlists/tracks, you can speed this up by fetching all playlist info in parallel. Doing this you will likely run into [rate limiting errors from the spotify API](https://developer.spotify.com/documentation/web-api/guides/rate-limits/), so you'll have to implement a backoff-retry strategy after the specified amount of time in  the `Retry-After` header. But it still comes out a lot faster than fetching the playlists synchronously. 

You can take a lot at how I implemented this on my end https://github.com/haykkh/what-the-playlist/pull/42/commits/14973bbfca5349b1b601eb943d62dc4b8362f489. There are definitely better ways to do it so i'm excited to see what you come up with!

**Comment by lfg6000** [comment]
i do like you suggestion, it really would speed up the fetching of playlist info, which is rather slow for users that select playlists with lots tracks.  i personally only curate ~12 playlists,  (~1200 tracks), so the slow loading time is not too annoying.   A bit of history... This app started off as a Python / QT app on my laptop.  Then i decided i wanted to run this app on multiple devices so i ripped off the QT front end and replaced it with html and flask.  Then i decided to make the app public.  So currently all the fetching of playlist info is done on the server in python (this is not optimal).  I am thinking that to implement your suggestion i really need to start over and make the client fetch all the playlist info in parallel.  I may do this in the future and i will look towards your what-the-playlist implementation as a reference.  If the current design or the redesigned app has lots of users online at the same time fetching playlist info i will probably have to ask Spotify to grant the app the Extended Quota Mode privilege.
