### ISSUE TITLE
Enable copy for "duplicates"

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#3]
Hi,
thanks for providing this great tool!
What do you think about adding move and copy (like in search) to the duplicates tab?
Use case: Find tracks from two different people's playlists and copy them to a "songs liked by both" playlist.

**Comment by lfg6000** [comment]
Thanks for the positive feedback.  It is fun to build apps that others find useful.
Thanks for the suggestion.  
I will think about how your suggestion fits in with the overall design and future plans for the app.
