### ISSUE TITLE
Make "Destination Playlist" sticky

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#4]
IMO it would be useful if "Destination Playlist" in "Move/Copy Selected Tracks to Another Playlist" would be preserved.

**Comment by lfg6000** [comment]
i am not sure what you mean by preserved.

copy and move are different in what they do.
copy = the selected tracks are added to the destination playlist and the source playlist is left unchanged
move = the selected tracks are added to the destination playlist and removed from the source playlist

**Comment by obetz** [comment]
the selection from the "Destination Playlist" drop-down list in the search tab should be preserved.
Example: I want to fill a new playlist called "foobar" and need repeated searches to find the tracks I want to copy/move to this list. Currently, after each search, the selection is cleared, so I need to select "foobar" again and again in the search tab. It would be great if the selection is kept between searches.

**Comment by lfg6000** [comment]
okay i now understand your suggestion and it is a very good suggestion.
agreed the search tab needs to remember the selected "Destination Playlist" between searches.
have coded the solution in my test environment.
need to do more testing before pushing the change to the web site.
will let you know when the change is live.

**Comment by lfg6000** [comment]
the above fix is live.
