### ISSUE TITLE
Ignore substrings in track and album or match for shorter length

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#6]
appendices like "(Bonus Tracks)", Deluxe, Expanded or Platinum Version in the album name or "edit", "radio edit", "remastered" in the track name disturbs duplicate search.

Possible solutions:
- Limit string comparison to the length of the shorter one (simple, universal)
- Apply some regex on the strings to remove known appendices

**Comment by obetz** [comment]
there are a lot of different strings to ignore, therefore it could be tricky to find short regular expressions. Examples: Remaster, Remastered, Remastered Version, 2005 Remastered, Remastered 2005, 

"` - \d* *Remaster*`" might work for the track name (didn't try yet)

Single, Mono, Stereo, Edit versions might be suppressed optionally, depending on the user's needs. Usually, I want only one version of a song in my collection, but there might be other users thinking differently.

Stripping everything after a "-" doesn't work well since track names like "Part-Time Lover" or "A-Me-Ri-Ca" would then be affected.

My "common part" approach doesn't work: Many track names are just a common word like "Nowhere" -> "Nowhere Man", Nowhere Fast", "Nowhere Girl" or "Here" -> "Here I Am" etc. so disregard this idea.

**Comment by lfg6000** [comment]
the regex approach is sound interesting.
it would be cool to apply an advanced search algorithm.
