### ISSUE TITLE
Indicate "Liked" status

### ISSUE THREAD

**Issue by obetz** [lfg6000/SpotifyFinder#7]
it would be nice if SpotifyFinder could indicate whether a track is "liked"

**Comment by lfg6000** [comment]
this is a another good idea and i will add it to the list of things to work on. 
spotify does not treat the 'liked songs' playlist like a normal playlist....the 'liked songs' playlist has a completely different set of api calls than the set of api calls for a regular user playlist.  this means the 'liked songs' playlist requires special code scatter thru out the code base.

**Comment by obetz** [comment]
Uh, didn'k now this. I'm not sure whether it's worth the effort then.
