### ISSUE TITLE
``Select All Tracks`` button for the "Tracks" tab

### ISSUE THREAD

**Issue by shannonfonseka** [lfg6000/SpotifyFinder#8]
I would like to suggest a feature to add a button <kbd>Select All Tracks</kbd> in the "Tracks" tab.
Since I want to sort my playlist in an alphabetical order and my playlist contains more than a thousand tracks, so selecting one thousand tracks is tiresome.

**Comment by lfg6000** [comment]
I am not sure i understand your suggestion.
On the tracks tab, or any other tab, you can click on any column header and the table resort.
If you click the playlist name column it will sort the playlists alphabetically.
If you click the track name column it will sort the tracks alphabetically.
If this does not help maybe you can provide a step by step use case so i can get an idea of what you are trying to do.

**Comment by shannonfonseka** [comment]
Oh I'm so sorry for the unclear instructions, let me correct it.

* I want to sort the tracks on a playlist in an alphabetical order. 
* After sorting the tracks in order. 
* I want to save the changes to a new/current playlist. To do that I have to _select tracks_ one by one. 
I have a playlist which has more than a thousand tracks. So selecting each and everyone would be tiresome.

I'd suggest to add a button called <kbd>Select All Tracks</kbd> (to check all the tracks in the playlist, instead of selecting one by one), and place it at the bottom of the "Tracks" page.

Thank you.

**Comment by lfg6000** [comment]
ok i now see what you are up to.
when you say save changes to a new/current playlist...do you mean using the move/copy feature?


by the way:
- in the windows spotify app you can sort a playlist by clicking on "# title" on the playlist screen
- in the android spotify app you can sort a playlist by scrolling down from the top of a playlist to expose the sort button

**Comment by shannonfonseka** [comment]
>  when you say save changes to a new/current playlist...do you mean using the move/copy feature?

Yes.

> * in the windows spotify app you can sort a playlist by clicking on "# title" on the playlist screen
> * in the android spotify app you can sort a playlist by scrolling down from the top of a playlist to expose the sort button

Oh yeah, I know about clicking the column and sorting, but that would sort only for me. It's just I want my playlist to be in order for other users as well. 😃 (I usually sort them in ascending order of the artist)

**Comment by lfg6000** [comment]
ok i get it and i think this is a good idea. thanks for the suggestion.
I will put this into the queue of things to work on and let you know when it is ready.
it maybe a little while before i am free to work on this.

**Comment by shannonfonseka** [comment]
You're welcome! 🙂

>I will put this into the queue of things to work on and let you know when it is ready.
it maybe a little while before i am free to work on this.

Sure, no problem. Just take your time!
Shall I close this Issue?

**Comment by lfg6000** [comment]
a select all button has been added to the tracks tab
also added a create playlist button to the tracks, search, artists tabs (allowing you to sort and then save)
also added a delete playlist button to the playlist tab
once again thanks for the suggestion
