### ISSUE TITLE
Sort artists by song count?

### ISSUE THREAD

**Issue by Switchbladd** [lfg6000/SpotifyFinder#9]
Is it now possible/can it be implemented to sort artists on the "Artists" tab by the number of their songs in selected playlists? Even without sorting, just seeing the number of songs would be cool. Now (as far as I understand) you can see the number of songs only if you click on a specific artist, which is not very comfortable.

**Comment by lfg6000** [comment]
it would be good to see the number of tracks for each artist.  will look into appending the number of tracks to the artists name.  it may be a while before i get to time to look into this.  will write when i have sorted this out.

**Comment by x-Misery** [comment]
> it may be a while before i get to time to look into this

Damn, you wasn't lying :sob:

**Comment by lfg6000** [comment]
artists tab:  artists track count column has been added to the artist name table. the artist track count column is sortable.
tracks tab:  playlist track count column has been added to the playlist name table. the playlist track count column is sortable.
be sure to let me know if you see any issues w/ this new functionality
